/* 
 * Decompression application using static arithmetic coding
 * 
 * Usage: ArithmeticDecompress InputFile OutputFile
 * This decompresses files generated by the "ArithmeticCompress" application.
 * 
 * Copyright (c) Project Nayuki
 * 
 * https://www.nayuki.io/page/reference-arithmetic-coding
 * https://github.com/nayuki/Reference-arithmetic-coding
 */

#include <cstdint>
#include <cstdlib>
#include <fstream>
#include <iostream>
#include <vector>
#include "BitIoStream.hpp"
#include "FrequencyTable.hpp"
#include "ArithmeticCoder.hpp"

using std::uint32_t;


int main(int argc, char *argv[]) {
	// Handle command line arguments
	if (argc != 3) {
		std::cerr << "Usage: " << argv[0] << " InputFile OutputFile" << std::endl;
		return EXIT_FAILURE;
	}
	const char *inputFile  = argv[1];
	const char *outputFile = argv[2];
	
	// Perform file decompression
	std::ifstream in(inputFile, std::ios::binary);
	std::ofstream out(outputFile, std::ios::binary);
	BitInputStream bin(in);
	try {
		
		std::vector<uint32_t> temp;
		for (int i = 0; i < 256; i++) {
			uint32_t freq = 0;
			for (int j = 0; j < 32; j++)
				freq = (freq << 1) | bin.readNoEof();  // Big endian
			temp.push_back(freq);
		}
		temp.push_back(1);  // EOF symbol
		SimpleFrequencyTable freqs(temp);
		
		ArithmeticDecoder dec(bin);
		while (true) {
			int symbol = static_cast<int>(dec.read(freqs));
			if (symbol == 256)  // EOF symbol
				break;
			out.put(symbol);
		}
		return EXIT_SUCCESS;
		
	} catch (const char *msg) {
		std::cerr << msg << std::endl;
		return EXIT_FAILURE;
	}
}
