/* 
 * Reference arithmetic coding
 * Copyright (c) Project Nayuki
 * 
 * https://www.nayuki.io/page/reference-arithmetic-coding
 * https://github.com/nayuki/Reference-arithmetic-coding
 */

import inputstreams.InputStreamFactory;

import java.io.IOException;
import java.io.OutputStream;


/**
 * Decompression application using static arithmetic coding.
 * <p>Usage: java ArithmeticDecompress InputFile OutputFile</p>
 * <p>This decompresses files generated by the "ArithmeticCompress" application.</p>
 */
public class ArithmeticDecompress extends ByteTransformer {
	
	public static void main(String[] args) throws IOException {
		new ArithmeticDecompress().commandLineMain(args);
	}
	
	@Override
	public void transformStream(InputStreamFactory inputStreamFactory, OutputStream out) throws IOException {
		try (BitInputStream in = new BitInputStream(inputStreamFactory.getStream());
				out) {
			FrequencyTable freqs = readFrequencies(in);
			decompress(freqs, in, out);
		}
	}
	
	
	// To allow unit testing, this method is package-private instead of private.
	static FrequencyTable readFrequencies(BitInputStream in) throws IOException {
		int[] freqs = new int[257];
		for (int i = 0; i < 256; i++)
			freqs[i] = readInt(in, 32);
		freqs[256] = 1;  // EOF symbol
		return new SimpleFrequencyTable(freqs);
	}
	
	
	// To allow unit testing, this method is package-private instead of private.
	static void decompress(FrequencyTable freqs, BitInputStream in, OutputStream out) throws IOException {
		ArithmeticDecoder dec = new ArithmeticDecoder(32, in);
		while (true) {
			int symbol = dec.read(freqs);
			if (symbol == 256)  // EOF symbol
				break;
			out.write(symbol);
		}
	}
	
	
	// Reads an unsigned integer of the given bit width from the given stream.
	private static int readInt(BitInputStream in, int numBits) throws IOException {
		if (numBits < 0 || numBits > 32)
			throw new IllegalArgumentException();
		
		int result = 0;
		for (int i = 0; i < numBits; i++)
			result = (result << 1) | in.readNoEof();  // Big endian
		return result;
	}
	
}
